### ISSUE TITLE
Need a quick sanity check/confirmation on failure messages. 

### ISSUE THREAD

**Issue by rromanchuk** [palkan/action_policy#108]
Ok so i'm i've spent an embarrassing amount of time on something today and i just want to make sure i i'm not hallucinating.  I wanted to assert that failures are actually returning the messaging per my localization file. I've got plenty of tests but never actually inspected until i noticed a bunch of customer support issues with the generic case. 

I have a semi complex setup with with name spaces, non resource  backed policies etc etc etc, so i figured it was user error.  So i threw in a bunch of debugging like below.

```ruby
rescue_from ActionPolicy::Unauthorized do |ex|
      message = ex.result.reasons.full_messages.first
      logger.info "[ActionPolicy::Unauthorized] Policy: #{ex.policy}, Rule: #{ex.rule}, Identifier: #{ex.policy.identifier}, Message: #{message}" #unless Rails.env.test?
      raise "#{ex.policy.identifier} missing an explanation. Responsible trigger: #{ex.policy}##{ex.rule}" if message.nil?
      render_policy_error(message: message)
  end
```

I turned on raise on missing translation, and i triple checked  my keys were resolving correctly. `ex.result.reasons.full_messages.first` would alway return nil, even if i ran manual I18n calls and it worked. I finally got it working when i randomly used `allowed_to?` in 

I RTFM again and carefully read translation lookup rules https://actionpolicy.evilmartians.io/#/i18n and confirmed resolution was  working as intended. I also read the section on failure reasons 

> Action Policy allows you to track failed allowed_to? checks in your rules.

I read that previously, but i assumed that meant to chain **multiple** reasons. I still assumed if i just use !authorize, and the same translation steps would run, even with a hardcoded `false`.   

```ruby

class UserPolicy < ActionPolicy::Base
  def show?
    false
  end
end

class UsersController < ApplicationController
  def show
    authorize! 
  end
end
```

```yaml
en:
  action_policy:
    policy:
      user:
        show?: "This is my error message"
```
I think i might be missing something fundamental?

**Comment by palkan** [comment]
Hey @rromanchuk! Have you figured it out?

`ex.result.reasons` only contain the nested `allowed_to?` / `check?` calls, not the rule itself. The message for the rule itself could be accessed through `ex.message`.
