### ISSUE TITLE
Default policy for namespace

### ISSUE THREAD

**Issue by jfouse** [palkan/action_policy#111]
What do you think about supporting a namespace-specific default policy? There may be situations in which you may not want e.g. a missing Admin::FooPolicy to fall through to the base FooPolicy, but rather use some Admin::DefaultPolicy instead.

For my current purpose it could be as simple as the `NAMESPACE_LOOKUP` resolver in LookupChain supporting an additional default_policy param that gets returned if `#lookup_within_namespace` doesn't find anything, like this:

    # Lookup within namespace when provided
    NAMESPACE_LOOKUP = ->(record, namespace: nil, default_policy: nil, **) {
      next if namespace.nil?

      policy_name = policy_class_name_for(record)
      lookup_within_namespace(policy_name, namespace) || default_policy
    }

The key of course is to have the namespace resolver actually return something before the final inference resolver gets called.

Obviously I can tweak the lookup chain for my own app, just thought I'd mention the need in case it seems like a useful addition.

**Comment by palkan** [comment]
This sounds to me as a combination of two options:
- `strict_namespace: true` — only lookup within a current namespace and halt the lookup chain with `nil` if nothing was found
- `default_policy_class` fallback method (which is called if `ActionPolicy.lookup` return `nil`).

That would require changes in the `lookup_chain.rb` (currently, it's impossible to fail-fast) and in the `ActionPolicy.lookup` (something like `fallback_policy:` option).

Then, in your _behaviour_ you call `authorize! smth, strict_namespace: true` and define a method:

```ruby
def default_policy_class
  DefaultPolicy
end
```

Probably, we need something like `#default_policy_lookup_options` to reduce the boilerplate:

```ruby
def default_policy_lookup_options
  {strict_namespace: true, fallback_policy: DefaultPolicy}
end
```



Does this sound like a solution?
