### ISSUE TITLE
Problem with method check? in the policy

### ISSUE THREAD

**Issue by delavaler** [palkan/action_policy#113]
### Tell us about your environment

**Ruby Version:** 2.7.1p83

**Framework Version (Rails, whatever):** Rails 6.0.2.2

**Action Policy Version:** action_policy (0.4.3)

**Reproduction Script:** https://github.com/delavaler/script/blob/master/check_bug.rb 

### What did you do?
@palkan Hi
I want to check in the policy the rule from another policy, using this instruction https://actionpolicy.evilmartians.io/#/writing_policies?id=calling-other-policies

When `check?` should return true it works fine

When `check?` should return false I get error `<NoMethodError: undefined method `reasons' for nil:NilClass>`

 in the 192 line `gems/ruby-2.7.1/gems/action_policy-0.4.3/lib/action_policy/policy/reasons.rb:189 ActionPolicy::Policy::Reasons#allowed_to?:`

**Comment by palkan** [comment]
Thanks for the reproduction! I'll take a look and come back with a fix.

**Comment by palkan** [comment]
Fixed in master.

Just a reminder, that this is not a _designed_ way of calling policy rules. You should use `apply(rule_name)` instead of calling method directly unless you know what are you doing)

**Comment by delavaler** [comment]
Thank you!

**Comment by austenmadden** [comment]
@palkan 😕 what if you want to account for `alias_rule`? `apply` does not factor in the aliases while `authorize!` and `allowed_to?` (and `check?`) do. This has come up when writing tests for policies.

To get around this issue without the fix in master I've been writing `my_policy.apply my_policy.resolve_rule(:my_rule?)`. However, that feels dirtier than using `allowed_to?` directly.
