### ISSUE TITLE
Testing issues.

### ISSUE THREAD

**Issue by pelted** [palkan/action_policy#114]
Trying to test my admin policies and struggling a bit with this.

Minitest with Rails 6 and Trestle Admin. In app ActionPolicy seems to be working as expected, but its testing that has me stumped. This is the super basics to illustrate what's going on. The first test passes as expected. The second, testing that the administrators index page is authorized does not pass.

```ruby
# administrator_policies_test.rb

class AdministratorPoliciesTest < ActionDispatch::IntegrationTest
  include Trestle::Engine.routes.url_helpers
  include ActionPolicy::TestHelper

  setup do
    @admin = create(:administrator)
  end

  teardown do
    sign_out
  end

  # This test works
  test 'can show own admin details' do
    sign_in_as(@admin)
    assert_authorized_to(:show?, @admin, with: AdministratorPolicy) do
      get administrators_admin_url(@admin)
    end
  end

  # This test fails '...but no such authorization has been made.'
  test 'can show admin index' do
    sign_in_as(@admin)
    assert_authorized_to(:index?, @admin, with: AdministratorPolicy) do
      get administrators_admin_index_url
    end
  end
end
```

```ruby
# administrator_policy.rb

class AdministratorPolicy < ApplicationPolicy
  def index?
    Rails.logger.debug(user) # logs instance of the admin test user as expected
    true
  end

  def show?
    user.id == record.id
  end

  def update?
    user.id == record.id
  end

  def destroy?
    user.super_admin? && (user.id != record.id)
  end
end
```

```ruby
# administrators_admin.rb

Trestle.resource(:administrators) do
  before_action only: %i[index new] do
    authorize! :user, with: AdministratorPolicy
  end

  before_action only: %i[show update destroy] do
    authorize! instance, with: AdministratorPolicy
  end
  ...
end
```

Side question, how would you all test unauthorized? `assert_authorized_to` catches `ActionPolicy::Unauthorized` so `assert_raises` doesn't work and in my app I rescue_from ActionPolicy::Unauthorized in order to display a flash message and redirect back.

**Comment by palkan** [comment]
The second argument for `assert_authorized_to` is the authorization target. In your case it's a `:user` symbol. Try to change the test to:

```ruby
test 'can show admin index' do
    sign_in_as(@admin)
    assert_authorized_to(:index?, :user, with: AdministratorPolicy) do
      get administrators_admin_index_url
    end
end
```

It should pass. Probably, it's better to change `:user` to `instance`.

> how would you all test unauthorized? 

If you want to the side effects of a missing authorization, you shouldn't use `assert_authorized_to`. As you noticed, it catches the exception. So, don't use it and let `rescue_from` to the trick.

**Comment by pelted** [comment]
I think I wrapped my head around this a little better. I found the little part in the docs about decorators, and after creating one specific to Trestle Admin's oddities things are a bit better. The policy look up was a problem, but that is resolved now.

As for testing side effects of a missing authorization I was going about it wrong. I was trying to test the wrong things.
