### ISSUE TITLE
skipping authorize dynamically

### ISSUE THREAD

**Issue by namiwang** [palkan/action_policy#117]
This is a feature request regarding skipping/canceling a planned authorize call.

Say I've added `verify_authorized` in `ApplicationController`, and in `PostController` I want to do something like this:

```
def create
  head 401 and return unless current_user

  @post = Post.find(...)
  ... 
end
```

Since I'm already returning a 401, I wouldn't want an unnecessary authorize check. I don't know if auto-skipping-on-4xx is a good idea, but at least is there any way I can do this

```
if not current_user
  cancel_authorize # or reuse skip_verify_authorized, dk if that's a good name
  head 401 and return
end
```

Sure for this case, I can and should use a `before action`. So maybe not a high-demanded feature :)

Thanks!

**Comment by palkan** [comment]
That's a useful feature :) Let's add it.

`skip_verify_authorized` sounds good to me.
