### ISSUE TITLE
Handling Generic authorization failures with dependant records

### ISSUE THREAD

**Issue by lifeiscontent** [palkan/action_policy#121]
### Tell us about your environment

**Ruby Version:** 2.6.6

**Framework Version (Rails, whatever):** 5.2.4.3

**Action Policy Version:** 0.4.3

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

### What did you do?

Hey @palkan hope you're doing well.

There's a feature we're currently working on that deals with authorization, but also in GraphQL we need to return records related to the failure.

A brief outline of the requirements are:

there may be reasons which are not hard requirements for the authorization.
there may be reasons which are hard requirements for the authorization.
there may be conflicting records that need to be returned in order to "fix" the authorization failure.

specifically, the last requirement here is what's currently blocking me. Have you ever dealt with a requirement like this before in GraphQL?

I'm curious to hear your thoughts around something like this.

in terms of the UX, we'd like to check the authorization, and if it fails, the "conflicting record" that is returned will be acted on.

if you need more context I'd be happy to share more, but I just wanted to get the conversation going.

### What did you expect to happen?
N/A

### What actually happened?
N/A

**Comment by palkan** [comment]
> in terms of the UX, we'd like to check the authorization, and if it fails, the "conflicting record" that is returned will be acted on.

Sounds like something we added reasons details support for. See [tests](https://github.com/palkan/action_policy/blob/863624adefa4a55a4cfc8eb801e873b40d7790e3/test/action_policy/policy/reasons_test.rb#L133-L194) and [docs](https://actionpolicy.evilmartians.io/#/reasons?id=detailed-reasons).

Does it sounds like something you're looking for?

If not, I would be glad to get more context or even code examples )

**Comment by lifeiscontent** [comment]
@palkan I think this might just need to be something custom in our GraphQL layer.

the context around the feature is basically something like this:

We want to do an action, but in order to do said action, we need to check that there is not a conflicting record that is preventing us to move forward with the action.

if a user is applying for a job, we want to make sure there is not a current job application they have with another company before letting them apply to another company.

If they indeed want to apply for a job with another company, they have the option to withdraw the job application.


so the flow of data is as follows:

- check if canApply?
- if they can't apply, return the job application that is conflicting.
- run mutation to withdraw
- continue back to original flow for new job application.

**Comment by palkan** [comment]
Let me try to sketch the implementation:

```ruby
def apply?
  check?(:conflicting_application?)
end

def conflicting_application?
  another_application = find_conflicting_application
  return unless another_application

  # keep conflicting application id in the details
  details[:conflicting_application_id] = another_application.id
  false
end
```

Then your `canApply` field would contain the following:

```json
"canApply": {
  "value": false,
  "reasons": {
     "details": "{\"conflicting_application_id\": <ID>}"
  }
}
```

Then, your JS client could get the id of the conflicting application from the `details` field. So, you don't need to request an ID from the server.

**Comment by lifeiscontent** [comment]
@palkan that's an interesting idea, thank you for your insight!
