### ISSUE TITLE
symbol policy lookup in namespace

### ISSUE THREAD

**Issue by skojin** [palkan/action_policy#122]
### Tell us about your environment

**Ruby Version:** 2.6.2

**Framework Version (Rails, whatever):**  rails 6.0.3.1

**Action Policy Version:** action_policy (0.4.3)

### What did you do?
```
class ReportPolicy < ApplicationPolicy
  def manage?
    true
  end
end

class Report::Default < ApplicationController
  def index
    authorize! :report
  end
end
```
### What did you expect to happen?
I expect that ReportPolicy will be found according to 
https://actionpolicy.evilmartians.io/#/lookup_chain and https://actionpolicy.evilmartians.io/#/namespaces

### What actually happened?
I got error
`Couldn't find policy class for :report (Symbol)`

If I rename policy to Report::ReportPolicy then it found

**Comment by palkan** [comment]
Thanks for reporting!
Fixed and released in 0.4.4.
