### ISSUE TITLE
rule mistypes

### ISSUE THREAD

**Issue by skojin** [palkan/action_policy#139]
I often do following error, forget to add '?' to rule when call `authorize! Model, to: :create`, then default rule work, and I spend some time to find where is a error. 

I suggest to raise an error when I ask permission for rule that not and with "?"

**Comment by palkan** [comment]
I think, we can add a configuration parameter to enforce predicate names (`ActionPolicy.enforce_predicate_rules_naming = true`, false by default).
Would you like to propose a PR?

**Comment by skojin** [comment]
yes, I will do it

**Comment by skojin** [comment]
@palkan please check my PR, I recently get this mistype problem again )
