### ISSUE TITLE
rspec and policy.apply sample

### ISSUE THREAD

**Issue by skojin** [palkan/action_policy#140]
This spec example, used apply method but it not work with aliasing
https://github.com/palkan/action_policy/blob/master/docs/testing.md
`subject { policy.apply(:update?) }`

I think it better replace with
`subject { policy.allowed_to?(:update?) }`
it will be less confusing

**Comment by palkan** [comment]
> not work with aliasing

That's intentional: the idea is to test policy rules, not configuration. Aliases should be tested at the _behaviour_ level (e.g., controller).
