### ISSUE TITLE
ruby 3.0.0 syntax errors

### ISSUE THREAD

**Issue by chaadow** [palkan/action_policy#141]
Hi happy holidays!!!

### Tell us about your environment

**Ruby Version:** 3.0.0

**Framework Version (Rails, whatever):** 6.1

**Action Policy Version:** 0.5.4

**ruby next core Version:** 0.11.0 ( released december 24th)

**Reproduction Script:** 
by running the same reproduction script with `ruby <reproduction_script.rb>` i get the same errors as in my application.

I'm having 3 kind of ruby syntax errors repeated multiple times

For example this :
```
SyntaxError: /Users/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/action_policy-0.5.4/lib/action_policy/utils/pretty_print.rb:135: syntax error, unexpected symbol literal
...d_name).source.then(&Unparser.:parse)
```
or this (many of them actually): 
```
SyntaxError: /Users/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/action_policy-0.5.3/lib/action_policy/behaviours/policy_for.rb:14: syntax error, unexpected ',', expecting =>
          **{namespace, context, allow_nil, default}
```

and this (many of them as well)
```
Users/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/action_policy-0.5.4/lib/action_policy/policy/authorization.rb:82: syntax error, unexpected instance variable
...  end => @authorization_targets
...         ^~~~~~~~~~~~~~~~~~~~~~
````
### What did you do?
I tried running rails test or even any rails command that would require this gem.

### What did you expect to happen?
no syntax errors XDD 
### What actually happened?
syntax errors XD

I managed to fix them by manually updating the gem and fix the syntax errors, I could make a PR but i believe this gem uses ruby-next ( i don't  quite understand how it works but i guess under the hood it generate ruby syntax that is valid... at runtime maybe?? ) so I think my PR would be useless

**Comment by palkan** [comment]
Thanks for reporting! Will fix it soon.

(The final Ruby 3.0 syntax is a bit different from what we had earlier, e.g., right-hand assignment, so it becomes invalid).

**Comment by palkan** [comment]
Fixed and released in 0.5.5

**Comment by chaadow** [comment]
@palkan thanks just tested it now! side question: i was wondering why I had this error:
```
yntaxError: /Users/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/action_policy-0.5.4/lib/action_policy/utils/pretty_print.rb:135: syntax error, unexpected symbol literal
...d_name).source.then(&Unparser.:parse)
```

but it seems that you didn't need to fix it. Thanks!

**Comment by palkan** [comment]
> `then(&Unparser.:parse)`

This ^ `.:` is a method reference operator which was added to 2.7-dev but then reverted. And I'm using it)

I don't need to fix it, RubyNext allows me to use it (it's translated into `then(&Unparser.method(:parse))`).

The gem is shipped with pre-transpiled source files for different versions (you can do `bundle open action_policy` and look at `lib/.rbnext` folder).

**Comment by chaadow** [comment]
thanks for the explanation! much appreciated
