### ISSUE TITLE
RSpec issues

### ISSUE THREAD

**Issue by lifeiscontent** [palkan/action_policy#151]
### Tell us about your environment

**Ruby Version:** 2.6.6p146

**Framework Version (Rails, whatever):** Rails 5.2.4.4

**Action Policy Version:** 0.5.5

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

### What did you do?

define policy

```ruby
class Billing::TagPolicy < ApplicationPolicy
  default_rule :manage?

  def manage?
    true
  end
end
```

define test

```ruby
RSpec.describe Billing::TagPolicy, type: :policy do
  let(:user) { build_stubbed :user }
  let(:record) { build_stubbed :billing_tag, name: 'TEST' }
  let(:context) { { user: user } }

  describe_rule :show? do
    failed 'when user is not an admin'
  end
end
```

### What did you expect to happen?

for the test to pass

### What actually happened?

NoMethodError: undefined method `show?' for #<Billing::TagPolicy:0x00007f82f9633750>

**Comment by lifeiscontent** [comment]
@palkan any ideas on how to fix this?

**Comment by lifeiscontent** [comment]
@palkan I notice in the rails console when I called apply I get a no method error, but when I call allowed_to? it works as expected.

```
[16] pry(main)> policy.apply(:show?)
NoMethodError: undefined method `show?' for #<Billing::TagPolicy:0x00007fa2f9214af0>
from /Users/lifeiscontent/.rvm/gems/ruby-2.6.6/gems/action_policy-0.5.5/lib/.rbnext/3.0/action_policy/policy/core.rb:101:in `public_send'
[17] pry(main)> policy.allowed_to?(:show?)
=> true
```

**Comment by palkan** [comment]
`#apply` doesn't use aliases; you should test the actual rule instead (i.e., `describe_rule :manage?`). That's intentional. See #140.
