### ISSUE TITLE
Syntax error in authorization

### ISSUE THREAD

**Issue by corroded** [palkan/action_policy#154]
https://github.com/palkan/action_policy/blob/ff8ad8df86c62f330df52d155851e477d31862fd/lib/action_policy/policy/authorization.rb#L69

We use dependabot to update gems automatically and our test suite fails because multiple specs are hitting this syntax error. I'm assuming it's for a future ruby version?

Do we also need to require `ruby-next` now? 

Stack trace:

```
bin/rails db:create
rails aborted!
SyntaxError: .../vendor/bundle/ruby/2.6.0/gems/action_policy-0.5.6/lib/action_policy/policy/authorization.rb:69: syntax error, unexpected ',', expecting => 
...ation_targets[id] = {allow_nil, optional}
...                              ^
.../vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
.../vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
```

**Comment by palkan** [comment]
Sorry for that, that release was broken (see #155).

Published a fix (0.5.7).
