### ISSUE TITLE
0.5.6 depends on ruby-next, not ruby-next-core

### ISSUE THREAD

**Issue by haines** [palkan/action_policy#155]
0.5.6 introduces lots of transitive dependencies, maybe it wasn't transpiled before releasing?

https://rubygems.org/gems/action_policy/versions/0.5.6
<img width="185" alt="Screenshot 2021-03-04 at 08 29 17" src="https://user-images.githubusercontent.com/785641/109933859-c45f9f00-7cc3-11eb-8012-c00d59683ea1.png">

https://rubygems.org/gems/action_policy/versions/0.5.5
<img width="182" alt="Screenshot 2021-03-04 at 08 29 27" src="https://user-images.githubusercontent.com/785641/109933888-cb86ad00-7cc3-11eb-9f68-6dcaac452717.png">

**Comment by palkan** [comment]
🤦‍♂️ I need to invest more time in automated releases to avoid such mistakes in the future :(

Thanks for catching this!

Release 0.5.7.

**Comment by haines** [comment]
No worries, thanks for fixing!
