### ISSUE TITLE
Rails controller without associated model fails policy lookup even with :with option

### ISSUE THREAD

**Issue by brendon** [palkan/action_policy#161]
### Tell us about your environment

**Ruby Version: 2.7.3

**Framework Version (Rails, whatever): Rails 6.1.3.1

**Action Policy Version: 0.5.7

### What did you expect to happen?
I have a Rails controller (Admin::SiteMapsController) that doesn't have an associated Model.

I used to do:
```ruby
before_action :authorize!

private

def authorize!
  super with: Admin::SiteMapPolicy
end
```

within this controller and it would authorise with the `Admin::SiteMapPolicy` and not worry about the missing record.

### What actually happened?
I get this error:

```
Couldn't find policy class for [#<Admin::SiteMapsController:0x000000001b5a08>, "Couldn't find implicit authorization target for Admin::SiteMapsController. Please, provide policy class explicitly using `with` option or define the `implicit_authorization_target` method."] (Array)
```

I can get things to work by adding:

```ruby
def implicit_authorization_target
  ''
end
```

or passing an empty string as the record:

```ruby
def authorize!
  super '', with: Admin::SiteMapPolicy
end
```

It seems that the logic around the `:with` option has changed and it is no longer acceptable to not have a record object.

**Comment by palkan** [comment]
Added a reproduction test and it passes. Could you take a look please (see above)? Maybe, I'm missing something.

**Comment by brendon** [comment]
Hi @palkan, at a quick glance, is there actually a `User` class present? If so, this won't trigger the problem. `ActionPolicy` needs to be unable to classify and constantise a class based on the controller class name in order for this to appear.

In my case I don't have a `Admin::SiteMap` or `SiteMap` model.

**Comment by palkan** [comment]
>  is there actually a User class present? If so, this won't trigger the problem

You're right. Now I can reproduce it.
And I would say that defining  `implicit_authorization_target` is the best solution to this.

Even though we explicitly define the policy class via `with`, we still need a record. It's not safe to assume that all the checks are _headless_. The goal is to avoid unexpected and hard to debug `Undefined method 'foo' for nil:NilClass` exceptions.

So, in your case it probably makes sense to do the following:

```diff
- def authorize!
-   super with: Admin::SiteMapPolicy
- end
+ def implicit_authorization_target
+   :site_map
+ end 
```

**Comment by brendon** [comment]
Thanks @palkan, that worked perfectly. Hopefully this will help anyone else with an edge case like this :)
