### ISSUE TITLE
Default policy lookup options

### ISSUE THREAD

**Issue by kevynlebouille** [palkan/action_policy#162]
### Tell us about your environment

**Ruby Version: 2.7.3**

**Rails Version: 6.1.3.1**

**Action Policy Version: 0.5.7**

### What did you do?

I want to use `strict_namespace` option (set to true), but don't find how to use it. (in ApplicationPolicy ?, completely rewrite lookup_chain ?) Use options with `allowed_to?` could be redundant.

In #111 issue, you wrote about an `default_policy_lookup_options` method.

Cheers,
Kevyn

**Comment by palkan** [comment]
I think, it'd be a useful to have this as a global option, e.g., `ActionPolicy.default_strict_namespace = true`. Would you like to propose a PR?

**Comment by kevynlebouille** [comment]
Closed in favor of #169
