### ISSUE TITLE
rspec testing of alias defined in `alias_rule` fails

### ISSUE THREAD

**Issue by danleyden** [palkan/action_policy#165]
### Tell us about your environment

**Ruby Version: 2.7.2**

**Framework Version (Rails, whatever): rspec**

**Action Policy Version: 0.5.7**

**Reproduction Script:**

```ruby
require 'spec_helper'
require 'action_policy/rspec/dsl'

class MyPolicy < ActionPolicy::Base
  # make the user optional to simplify - not relevant in this test.
  authorize :user, optional: true

  alias_rule :using_alias?, to: :my_rule?

  def my_rule?
    true
  end
end

describe MyPolicy, type: :policy do
  describe_rule :my_rule? do
    # works correctly
    succeed
  end

  describe_rule :using_alias? do
    # raises NoMethodError - should pass
    succeed
  end
end
```

### What did you do?
1. define an `alias_rule` pointing to a defined rule
2. in an rspec test, create a `describe_rule` policy pointing to the alias
3. run the test

### What did you expect to happen?
the rule defined as `to` in the `alias_rule` should be processed

### What actually happened?
raises a `NoMethodError`

**Comment by palkan** [comment]
This is an intended behavior, you should only test the actual rules (that was one of the reasons for the current aliases design: avoid excess duplicate tests).

See also https://github.com/palkan/action_policy/issues/125#issuecomment-663496659

**Comment by danleyden** [comment]
Understand that it may be intended behaviour for alias_rule to be "syntactic sugar", however I really think this needs to be considered a little more.

The name of the rules form the interface of the policy (including when they're aliased). The caller shouldn't know or care that a rule is aliased or a real rule (that is very much an implementation detail inside the policy), so it should be possible to test that the interface provided is complete....

**Comment by palkan** [comment]
> so it should be possible to test that the interface provided is complete

Then all you need is to test whether the alias is defined. No need to test the rule itself.

**Comment by danleyden** [comment]
> > so it should be possible to test that the interface provided is complete
> 
> Then all you need is to test whether the alias is defined. No need to test the rule itself.

Then you're testing the implementation, not the behaviour...

A good test should assert that, for a given context, the behaviour is as expected. If the test asserts that the interface is an `alias_rule`, then it is the implementation of the policy rather than the intent which is being tested. 

Under this model, the test needs to know about the internals of not only the policy, but the ActionPolicy framework. This makes refactoring harder and results in brittle and/or pointless tests
