### ISSUE TITLE
possible CSS issue on docs?

### ISSUE THREAD

**Issue by jcquarto** [palkan/action_policy#168]
I was reading the excellent Action Policy write up at:

https://actionpolicy.evilmartians.io/#/quick_start

(and other pages there that show Ruby code)

I think there's a  CSS issue:  the way the code is being presented it is very difficult to read the punctuation styled in gray-on-black on the code samples.   For example, this code:
`before_action :load_post, only: [:edit, :update, :destroy]`
reads like this
`before_action load_post, only [edit, update, destroy]`
(unless of course you squint very hard). It seems to be especially difficult w.r.t. the colons which are very subtle, compared to the brackets which more readily stood out.

I've a mid-level Rails skillset, and it still took me a bit of "why isn't this working, i'm doing exactly what they said!" debugging to realize the answer was right in front of me. Certainly for a new developer this would be a larger hurdle (when in reality it isn't a hurdle at all, it's just the CSS)

Is there some easy easy way you can tweak the CSS so the contrast between the gray and the black is more obvious? I think it would save others who are new to Action Policy some valuable time.

Hopefully this is the easiest "bug" (really, more of a suggestion) you get all year!  Thanks for your work on this very useful gem

**Comment by palkan** [comment]
Thanks for reporting!

Changed the background to a light one (that's the quickest fix).
