### ISSUE TITLE
Question: using strict_namespace option from #authorize!

### ISSUE THREAD

**Issue by carlost** [palkan/action_policy#169]
### Tell us about your environment

**Ruby Version:** 2.7.3

**Framework Version (Rails, whatever):** Rails 6.1.3.2

**Action Policy Version:** 0.5.7

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) ... i would love to have used this but a number of these tests were failing right out of the gate:

> \# Running:
> 
> E
> 
> Error:
> TestBugReproduction#test_update_succeed:
> ActionController::UrlGenerationError: No route matches {:action=>"update", :controller=>"users", :target=>"guest", :user=>"admin"}
>     /Users/cefernan-local/.rvm/gems/ruby-2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/formatter.rb:44:in `path'
>     /Users/cefernan-local/.rvm/gems/ruby-2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route

### What did you do?

I passed `namespace: Admin, strict_namspace: true` options to `authorize!`

### What did you expect to happen?

`authorize!` to lookup the appropriate policy class using the `Admin` module namespace and to NOT cascade the search to policy files outside of that namespace.

### What actually happened?

> ArgumentError: unknown keyword: :strict_namespace

While the `namespace` option is exposed to the most likely ActionPolicy methods I would invoke from a rails controller/service/view, such as `authorize!` or `allowed_to?`, it appears that `strict_namespace` is not available.

0.5.7 source for ActionPolicy::Behaviors::PolicyFor#policy_for:
https://github.com/palkan/action_policy/blob/124d9e6fecfa9767cc0946a51ed42dc70402b6e4/lib/action_policy/behaviours/policy_for.rb#L11-L17

`strict_namespace` is not passed to `ActionPolicy::lookup`

Is preventing the use of `strict_namespace` from `authorize!` a defect or an explicit choice?

After reading your comment [here](https://github.com/palkan/action_policy/issues/111#issuecomment-615377967), i assumed that `strict_namespace` could be used with `authorize!`.

If it is an explicit choice, should i just pass a default `NullPolicy` to `authorize!` that would effectively shut the user out of all behavior ... or monkey with the policy lookup chain?

**Comment by palkan** [comment]
> Is preventing the use of strict_namespace from authorize! a defect or an explicit choice?

Looks like a defect 🙁

@kevynlebouille Could you please take a look? Maybe, we can fix it in #162 by moving the fallback from LookupChain to the behavior (`policy_for`)?

**Comment by kevynlebouille** [comment]
Hi @palkan ,

I've created a new PR #172 to replace PR #167 :)

**Comment by palkan** [comment]
Merged in #178
