### ISSUE TITLE
Best practice for authorising Rails controller methods without a model

### ISSUE THREAD

**Issue by jacobwalkr** [palkan/action_policy#17]
We have a number of Rails controllers that are not directly tied to a model. For example, in our app, the AdminController does not have a corresponding Admin model and the StaffController links ultimately to the User model. In these instances, we can use something like `authorize! with: AdminPolicy` to specify.

Is there a way to do this more tidily, without using `with:`? For example, by falling back on a policy that matches the controller name instead of a model name? 

We've tried to do it by adding a custom probe to the lookup chain, but the `record` in these cases is `nil` and we can't find a robust way of accessing the controller name from the probe.

**Comment by palkan** [comment]
> but the record in these cases is nil

Yeah. We consider that the _implicit_ policy is backed by a model.

Probably, it make sense to an API to make it customizable, say:

```ruby
class ApplicationController < ActionController::Base
  # invoked when authorize! is called without an argument
  def implicit_authorized_record
     # `super` is a current implementation that tries to find a model by controller name
     #  then we can extend lookup chain to handle Symbols as records
     super || controller_name.to_sym
  end
end
```

What do you think?

**Comment by gururuby** [comment]
Hi, may be pass the setting as a parameter? Or does it go against the architecture of gem? For example, create a class method for configuring a policy within a specific controller? for example: `authorized as: :controller_name`, or `authorized as: -> { something value }`

**Comment by jacobwalkr** [comment]
@palkan I'd be very happy with that solution. Would it preserve the controller's namespace?

**Comment by jacobwalkr** [comment]
Ah, as long as there's a way of doing it! The whole namespace is quite useful for the way we're structuring our policies.

**Comment by palkan** [comment]
> Would it preserve the controller's namespace?

> nope, you'll need controller_path in order to preserve the namespace.

Actually, ActionPolicy could take care of the namespace, so in your custom lookup method you'll be able to use it:

```ruby
SYMBOL_LOOKUP = ->(record, namespace: nil, **) {
  next unless record.is_a?(Symbol)
  
  # Generate a name for a policy,
  # for example, :admin -> AdminPolicy
  policy_name = "#{record.to_s.classify}Policy"
 
  lookup_within_namespace(policy_name, namespace)
}
```

NOTE: `namespace` is a result of calling `authorization_namespace` method which by default returns the controller's namespace (i.e. _outer_ module) but could be overridden.

Btw, I've just realized that there is another way to infer policies from controllers without dealing with lookup chains:

```ruby
class ApplicationController < AC::Base
  # Add policy_name method to your ApplicationController
  def self.policy_name
     # ...
  end

  # and then override implicit record
  def implicit_authorized_record
    super || self
  end
end
```

**Comment by jacobwalkr** [comment]
@palkan Passing the controller as the resource seems like a tidier solution than passing symbols! It also means that the controller would be accessible to the policy. I haven't thought of a concrete advantage to that but it's more flexible than just a bit o' text :)

**Comment by palkan** [comment]
Symbol lookup has been added in #46 and will be released in the next version.
