### ISSUE TITLE
allowed_to? without record but given with and context options fails

### ISSUE THREAD

**Issue by leehericks** [palkan/action_policy#176]
**Ruby Version:**
Ruby 3.0.1

**Framework Version (Rails, whatever):**
Rails 6.1.4

**Action Policy Version:**
0.5.7

### What did you do?

I have a navigation bar and some links are conditional, like if you are a teacher you can see the students' reflections:

```erb
<% if allowed_to?(:index?,  with: Lms::Groups::ReflectionPolicy, context: { group: group }) %>
  <%= link_to... %>
<% end %>
```

### What actually happened?

- allowed_to? when called without a record seems to ignore the options and raises ActionPolicy::NotFound.
- When called with record = nil, ArgumentError, Record must be specified
- When called with record = group, works fine...but this is a policy about seeing the reflections but rendering the navigation doesn't have an array of reflections, nor does it need them for authorization, so this is completely wrong. This is exactly why I use the context to pass the group for authorization. I find that I need roughly a policy per controller but the real authorization logic doesn't necessarily need to be digging through the record, and on top of that :index? is the black sheep!

**Comment by leehericks** [comment]
Of course I could just test if the current user is a teacher in the group, but then I would be littering the authorization code in my view partial.

**Comment by leehericks** [comment]
```erb
<% if allowed_to?(:index?, Lms::Lessons::Reflection, with: Lms::Groups::ReflectionPolicy, context: { group: group }) %>
```
I feel better about this but I'm still not sure if I'm doing this wrong or allowed_to? has a bug because allowed_to? can be "resourceless" in the controller.

**Comment by brendon** [comment]
https://actionpolicy.evilmartians.io/#/caching?id=per-instance seems to show the context coming in from the controller. Is `group` set as a context at the controller level?

**Comment by leehericks** [comment]
The group could be set at the controller level and that would DRY up the call site a bit. Nice point!

It's not the part causing trouble though. The second parameter should be record or model class.

It can be inferred from the controller name or set with implicit_authorization_context but in this case the navigation is rendered across multiple controllers so it may just be that by design the class and policy must both specified in my case.

**Comment by brendon** [comment]
I had similar trouble recently I think: https://github.com/palkan/action_policy/issues/161

Not sure if that'll help at all. The docs on using this in the view layer are a bit sparse.

**Comment by palkan** [comment]
> The documentation does not explicitly say that calling authorized_scope means you don't need to call authorize!

Yeah, there is no such feature, because scoping not always means the action has been authorized.
In you case, using `skip_verify_authorized only: :index` makes sense.

Maybe, we can add an option to `authorized_scope` to mark action as authorized 🤔
