### ISSUE TITLE
Default scope configuration for active_record_relation is lost when using a custom base policy

### ISSUE THREAD

**Issue by shepmaster** [palkan/action_policy#199]
### Tell us about your environment

**Ruby Version:**

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]

**Framework Version (Rails, whatever):**

Rails 6.1.4.1

**Action Policy Version:**

0.6.0

**Reproduction Script:**

(I attempted to use [the template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb), but it fails to run before any changes are made)

### What did you do?

Following the [directions about a custom base policy](https://actionpolicy.evilmartians.io/#/custom_policy), I switched to a custom base from `ActionPolicy::Base`.

### What did you expect to happen?

My existing scopes defined with `scope_for :active_record_relation` and used via `authorized_scope(ModelName.all)` would continue to work.

### What actually happened?

```
ActionPolicy::UnrecognizedScopeTarget (Couldn't infer scope type for ModelName::ActiveRecord_Relation instance)
```

This appears to be because the scope setup has hard-coded `ActionPolicy::Base`:

https://github.com/palkan/action_policy/blob/aa686b635e8705992084b43975a0738d41fd8479/lib/action_policy/rails/scope_matchers/active_record.rb#L15-L19

**Comment by shepmaster** [comment]
My _real_ goal is to rename `user` to `identity` to match the rest of our application. The only way I see to do that is to involve a custom base. If there's a better way to remove / rename it, that would also solve my problem.

**Comment by palkan** [comment]
> This appears to be because the scope setup has hard-coded ActionPolicy::Base:

Correct. For a custom base class, you need to register scope matchers yourself; I will add it to the docs.

> If there's a better way to remove / rename it, that would also solve my problem.

Yeah, you can add the following to your base class:

```ruby
class ApplicationPolicy < ActionPolicy::Base
  authorization_targets.delete(:user)
end
```
