### ISSUE TITLE
feat: pass with: as string or symbol to perform policy lookup that respects the current namespace

### ISSUE THREAD

**Issue by erickreutz** [palkan/action_policy#203]
When overriding `authorization_namespace` and deciding the namespace based on the request context it would be nice if we could pass the `with:` param of `authorize` as a `string` or `symbol` and it would lookup the policy while respecting the current namespace.

**Comment by palkan** [comment]
Could you please provide an example (or a test case in the PR 😉) demonstrating a use case for this change?

**Comment by palkan** [comment]
Closed as stale
