### ISSUE TITLE
Class based lookup with strict namespace and matching explicit namespace doesn't work

### ISSUE THREAD

**Issue by benedikt** [palkan/action_policy#206]
### Tell us about your environment

**Ruby Version:** 3.0.3

**Action Policy Version:** 0.6.0

**Reproduction Script:** 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "minitest", "~> 5.15"
  gem "action_policy", "~> 0.6"

  gem "pry-byebug", platform: :mri
end

require "action_policy"

require "minitest/autorun"

module Namespaced
  class User; end
  class UserPolicy < ActionPolicy::Base; end
end

class TestBugReproduction < Minitest::Unit::TestCase
  def test_strict_lookup
    result = ActionPolicy.lookup(Namespaced::User, strict_namespace: true, namespace: Namespaced)
    assert_equal Namespaced::UserPolicy, result
  end
end
```

### What did you do?

I'm trying to restrict policy lookups to the shared namespace of the controller, the model and the policy by adding `authorization_strict_namespace` with a return value of `true` to the controller. Because the controller is namespaced as well `authorization_namespace` returns its namespace. 
I'm returning the correct, namespaced, model class from `implicit_authorization_target`.

This results in a policy lookup call that looks like this: 

```ruby
ActionPolicy.lookup(Namespaced::User, strict_namespace: true, namespace: Namespaced)
```

### What did you expect to happen?

I'd expect the policy lookup to return `Namespaced::UserPolicy`, because the given namespace matches the namespace of the model class and the policy class. 

### What actually happened?

The lookup is unsuccessful and raises a `ActionPolicy::NotFound` exception.

**Comment by palkan** [comment]
Thanks for the report!
Fixed and will be released soon.

**Comment by benedikt** [comment]
Thanks a lot! 👍
