### ISSUE TITLE
deprecation warning with Ruby 3.1

### ISSUE THREAD

**Issue by GoktugOzturk** [palkan/action_policy#207]
### Tell us about your environment

**Ruby Version:** 3.1.1

**Framework Version (Rails, whatever):** Rails 7.0.2.3

**Action Policy Version:** 0.6.0

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

### What did you do?
Initialize project

### What did you expect to happen?
Should work without errors 

### What actually happened?
Action Policy gives this deprecation warning
/home/appuser/vendor/bundle/ruby/3.1.0/gems/action_policy-0.6.0/lib/action_policy/ext/module_namespace.rb:24: warning: Refinement#include is deprecated and will be removed in Ruby 3.2

**Comment by palkan** [comment]
Thanks for the report! Working on it.

**Comment by GoktugOzturk** [comment]
Hi, I'm not sure if you're still working on this but wanted to write another comment since you closed this issue.
You've fixed some parts on the codebase with [this commit](https://github.com/palkan/action_policy/commit/185bb3dddf75fe7284f2ef09c4c846b07ea0db81)
But [module_namespace.rb](https://github.com/palkan/action_policy/blob/73daca0232b2eb7b632b811f83bcdfd307927b79/lib/action_policy/ext/module_namespace.rb#L24) still contains this problem. 

Also, another minor release with the changes would be appreciated
