### ISSUE TITLE
Add ability to authorize nil records if :with option is provided

### ISSUE THREAD

**Issue by ezekg** [palkan/action_policy#218]
### Tell us about your environment

**Ruby Version:** 3.1.2p20

**Framework Version (Rails, whatever):** 7.0.3.1

**Action Policy Version:** 0.6.1

**Reproduction Script:** https://gist.github.com/ezekg/127ed46a1ada80dd80b4321abf959b7c

### What did you do?

I attempted to authorize a `nil` record while providing `with:`. For example, when a user is attempting to replace a `nil` record with another record, we still want to assert that the user is authorized to do so, before doing so.

### What did you expect to happen?

That the provided policy would still be called with the `nil` record.

### What actually happened?

The following error was raised:

```
ArgumentError (Record must be specified):
```

### What workarounds have you tried?

The following monkey patches resolve the problem, one pulled in from #217:

```ruby
module ActionPolicy::Behaviour
  ##
  # Remove memoization of authorization context. This allows us to use
  # authorized_scope() before authorize!() in controllers for nested
  # resources, e.g. /posts/:post_id/comments.
  def authorization_context = self.class.authorization_targets.each_with_object({}) { |(k, m), o| o[k] = send(m) }

  ##
  # Allow nil :record in authorize!() calls. Sometimes we want to explicitly
  # authorize nil for certain policies, e.g. Post::AuthorPolicy#update?.
  # This also drops logic for implicit :record, which we don't use.
  def lookup_authorization_policy(record, **options) = policy_for(record:, **options)
end
```

### What do you suggest?

Add an option to allow authorizing `nil` records when an explicit policy is provided via `with:`.

For example, adding an `allow_nil:` option to `authorize!`.

**Comment by palkan** [comment]
I think, we could allow passing `nil` if `with` is specified explicitly without any additional options.

**Comment by ezekg** [comment]
That would be ideal. 🙂
