### ISSUE TITLE
NoMethodError: undefined method `params_filter' for MyPolicy:Class in tests

### ISSUE THREAD

**Issue by jclusso** [palkan/action_policy#225]
### Tell us about your environment

**Ruby Version: 3.0.4**

**Framework Version (Rails, whatever): 7.0.3**

**Action Policy Version: 0.6.3**

**Reproduction Script:**  
[bug_report_template.rb.zip](https://github.com/palkan/action_policy/files/10430461/bug_report_template.rb.zip)

### What did you do?

Use `params_filter` in a policy.

### What did you expect to happen?

Tests to work.

### What actually happened?

`NoMethodError: undefined method 'params_filter' for MyPolicy:Class` is raised.

**Comment by palkan** [comment]
Thanks for reporting!

Fixed and released in 0.6.4
