### ISSUE TITLE
Unknown policy scope type :active_record_relation

### ISSUE THREAD

**Issue by tomasc** [palkan/action_policy#228]
### Tell us about your environment

**Ruby Version:**
3.2

**Framework Version (Rails, whatever):**
7.0.4.1

**Action Policy Version:**
0.6.4

### What did you do?
Upgraded from `0.6.3` to `0.6.4`.

### What actually happened?
Unknown policy scope type `:active_record_relation`. Downgrading back to `0.6.3` resolves this issue.

**Comment by palkan** [comment]
Thanks for reporting.

Do you see this problem in development or other env? I think, it could be related to code reloading. Can you try disabling code reloading (`config.cache_classes = true`) and see if the issue persists?

**Comment by palkan** [comment]
I pushed a fix to master, could you please check it out?

**Comment by tomasc** [comment]
@palkan thanks a lot for the fix! I have tested by sourcing action_policy from master and re-running test suite of my app, and the issue seems to be resolved.
