### ISSUE TITLE
How Do I Test Resource-less Authorize?

### ISSUE THREAD

**Issue by Petercopter** [palkan/action_policy#238]
### Tell us about your environment

**Ruby Version:**
3.2.1

**Framework Version (Rails, whatever):**
Rails 7.x

**Action Policy Version:**
0.6.5

### What did you do?
https://actionpolicy.evilmartians.io/#/rails?id=resource-less-authorize

If I do this, how can I test it using RSpec?

```
class PostsController < ApplicationController
  def index
    authorize!
  end
end
```
```
describe '#index' do
  it do
    expect { get posts_path }.to be_authorized_to(:index?)
  end
end
```

### What did you expect to happen?
Test would pass. There doesn't seem to be a way to test without an object to authorize against.

```
def be_authorized_to(rule, target)
  ActionPolicy::RSpec::BeAuthorizedTo.new(rule, target)
end
```
### What actually happened?

```
Failure/Error: it { expect { get posts_path }.to be_authorized_to(:index?) }

ArgumentError: wrong number of arguments (given 1, expected 2)
```

**Comment by palkan** [comment]
Correct. In tests, you must be explicit about the authorization target object or the policy class that must be used. The goal of the test is to verify the correct policy has been used.

We can hardly infer the expected class from a test class (well, maybe, we can assume that `described_class` is a controller class, so we can get the name and turn it into a policy name, but that would made tests too vague). And I can see how that can lead to false positives: you change the controller name (say, PostsController > DrafsController); now a DraftPolicy is used implicitly and in tests we also implicitly check for it; but you might want to continue using PostPolicy—the test wouldn't catch this.

> If I do this, how can I test it using RSpec?

```ruby
expect { get posts_path }.to be_authorized_to(:index?, Post)

# or
expect { get posts_path }.to be_authorized_to(:index?, :post)
```

Though I think the following would be even better:

```ruby
expect { get posts_path }.to be_authorized_to(:index?).with(PostPolicy)
```
