### ISSUE TITLE
Add --parent option to policy generator

### ISSUE THREAD

**Issue by Spone** [palkan/action_policy#239]
## Feature request

When using `rails g action_policy:policy Page`, I'd like to be able to pass `--parent CustomPolicy`, so the generated policy looks like that:

```rb
class PagePolicy < CustomPolicy
  # ...
end
```

### Motivation

A similar `--parent` option [exists in Rails](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/rails/generators/active_record/model/model_generator.rb#L14).

**Comment by palkan** [comment]
Closed by #241

**Comment by Spone** [comment]
Thanks a lot @matsales28!
