### ISSUE TITLE
Update a documentation about #be_an_alias_of matcher

### ISSUE THREAD

**Issue by DenisZackharov** [palkan/action_policy#242]
I think that documentation need to tell about connecting a `#be_an_alias_of` matcher with adding a `require "action_policy/rspec"`, like you wrote it for `#be_authorized_to` matcher

`#be_an_alias_of` screen:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/78980031/230740700-3dcd3aae-832f-494b-895a-c51847009f15.png">

`#be_authorized_to` screen:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/78980031/230740741-557017f6-fa39-4c96-93d0-e3523014f8aa.png">

**Comment by DenisZackharov** [comment]
I make a PR https://github.com/palkan/action_policy/pull/243

**Comment by palkan** [comment]
Closed by #243
