### ISSUE TITLE
Documentation Contrast

### ISSUE THREAD

**Issue by baweaver** [palkan/action_policy#244]
Heya, was taking a look at the documentation site and noticed the contrast for the menu bar may be a bit low:

<img width="757" alt="Screenshot 2023-04-10 at 10 03 18 AM" src="https://user-images.githubusercontent.com/979723/230952451-66de0777-1507-42bd-88ad-bc1a757b2752.png">

If you take a look in web console it'll mention [AA and AAA contrast levels](https://usecontrast.com/guide):

<img width="1050" alt="Screenshot 2023-04-10 at 10 05 50 AM" src="https://user-images.githubusercontent.com/979723/230952877-2e2ffe7f-c847-46d5-9931-8f0c46b2e275.png">

Could we potentially switch it to a higher contrast color? If you'd like I can put out a PR for it, but the simple fix would probably be making the menu links white and the hover effect a darker background.

Quick example of changing it to white, and a css like `li { font-weight: 600; a { font-weight: 400; } }`:

<img width="477" alt="Screenshot 2023-04-10 at 10 08 19 AM" src="https://user-images.githubusercontent.com/979723/230953305-25bb1956-5355-4df9-9510-ceab79c1bf33.png">

Anyways, again I can put out a PR for any of that later if you'd like, but wanted to mention it as an issue first.

**Comment by palkan** [comment]
Thanks for the report!

I would be glad to merge a proposed quick fix 👍

**Comment by louim** [comment]
Hey @palkan, I just wanted to let you know that I think something is off with the select/highlight color:
![image](https://user-images.githubusercontent.com/923718/234667849-13a8ac9a-9a8d-4446-9019-10cb1ed1b8ba.png)

**Comment by palkan** [comment]
@louim Thanks! Fixed
