### ISSUE TITLE
Cannot use `controller_authorize_current_user` with `ActionPolicy::Base`

### ISSUE THREAD

**Issue by danieldraper** [palkan/action_policy#251]
### Tell us about your environment

**Ruby Version:** 3.2.0

**Framework Version (Rails, whatever):** 7.0.7.2

**Action Policy Version:** 0.6.5

**Reproduction Script:** https://gist.github.com/danieldraper/02b39a3cfb4593896acac1e92f410a69

### What did you do?
Setting `config.action_policy.controller_authorize_current_user = false` in `application.rb`

### What did you expect to happen?
To disable `authorize :user` default

### What actually happened?
Error `Missing policy authorization context: user`

### Possible problem

I believe this error exists when you generate an `ApplicationPolicy` that inherits from `ActionPolicy::Base`.

`ActionPolicy::Base` includes `ActionPolicy::Policy::Defaults` which has `base.authorize :user`. As far as I can see this bypasses `controller_authorize_current_user`.

This could also just be solved with a comment in the docs that point to https://actionpolicy.evilmartians.io/#/custom_policy and suggest creating your own base class as the option isn't compatible with the default base class?

**Comment by palkan** [comment]
The `controller_authorize_current_user` option only affects the controller configuration, it doesn't change the authorization context schema defined in policies. 

You can inherit from `ActionPolicy::Base` and add `authorize :user, optional: true` or `authorization_context.delete(:user)` (though it's an internal API).

Added a note to the Rails documentation.
