### ISSUE TITLE
0.6.7 breaks wrap_parameters

### ISSUE THREAD

**Issue by natematykiewicz** [palkan/action_policy#255]
### Tell us about your environment

**Ruby Version:**
3.2.2

**Framework Version (Rails, whatever):**
7.0.8

**Action Policy Version:**
0.6.7

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

I can't figure out how to reproduce it in the test suite, but wrapped parameters work on 0.6.6 and don't on 0.6.7. Though 0.6.6 has the [eager_load problem](https://github.com/palkan/action_policy/issues/252), so 0.6.5 is the last working version for us. I believe the problem, is that [this commit](https://github.com/palkan/action_policy/commit/01f3aa8c6877f4717a34838d3dc87dc3b98dbdaa) switches the load order and so `ActionController::Base` gets loaded before all of the initializers, and so my initializer no longer takes affect. I've found that if I edit the 0.6.7 source code in my app and delete this, my problem is resolved:

```ruby
begin
  ::ActionController::Base
rescue NameError
end
```

### What did you do?
Made an API call that expected `wrap_parameters` to work due to `Rails.application.config.action_controller.wrap_parameters_by_default = true` (a Rails 7.0 default)

### What did you expect to happen?
Expected a 200 response

### What actually happened?
Got a 400 due to a missing wrapped parameter

**Comment by palkan** [comment]
Thanks for reporting!

Looks like preloading base Rails classes wasn't a good idea (I wonder if we can add some warning to Rails when someone attempts to trigger load hook before initialization completes 🤔).

Pushed a fix to master. Please, give it a try.

**Comment by natematykiewicz** [comment]
No problem!

ActionPolicy on master passes my test suite, so your changes worked!

Also, I think this issue aims to do exactly what you're suggesting, for this very reason:
https://github.com/rails/rails/issues/50133

**Comment by palkan** [comment]
Thanks! Released in 0.6.8
