### ISSUE TITLE
How to test pre_checks

### ISSUE THREAD

**Issue by brendon** [palkan/action_policy#269]
I've had a look through the testing documentation and couldn't see any specific mention of the appropriate way to test `pre_check`s given they point to private methods on the policy. I can easily test their effects but it'd be cool to be able to test the method. Should I perhaps make the method public instead? :)

**Comment by palkan** [comment]
I usually test pre-checks via `#apply`, here is an example:

```ruby
test "#manage? returns false if record does not belong to account" do
  @cable.account = accounts(:hobbits)
  # No pre-checks invoked
  refute @policy.manage?
end

test "#manage? returns true if user is an admin" do
  @cable.account = accounts(:hobbits)
  @user.role = :admin

  # Using #apply to trigger pre-checks
  assert @policy.apply(:manage?)
end
```

**Comment by brendon** [comment]
Ah that's interesting! I've been exclusively testing with `policy.apply` this whole time. I'm using `rr` to mock out external calls to other policies and to also bypass pre-checks:

`mock(policy).deny_logged_out` where `deny_logged_out` was a pre-check private method.

Nice to know I can bypass them anyway by testing the actual public methods :)
