### ISSUE TITLE
cannot load such file -- action_policy/middleware (LoadError) after upgrading to 0.2.1

### ISSUE THREAD

**Issue by mad42** [palkan/action_policy#29]
**Ruby Version: 2.5.1

**Framework Version (Rails, whatever): rails 5.2.0

**Action Policy Version: 0.2.1

### What did you do?
updating from Action Policy 0.2.0 to 0.2.1

### What did you expect to happen?
normal behavior.

### What actually happened?
i can't launch rails server
`require': cannot load such file -- action_policy/middleware (LoadError)

### Rollback
rolling back to Action Policy 0.2.0 resolves the problem.

**Comment by palkan** [comment]
Thanks for the report!

Fixed in 0.2.2
