### ISSUE TITLE
Issue calling alias_rule when initializing policies

### ISSUE THREAD

**Issue by benoitongit** [palkan/action_policy#34]
Is intended that we can't call alias_rule from a policy instance?

```
class ArticlePolicy < ApplicationPolicy
  alias_rule :edit?, to: :update?

  def update?
    true
  end
end
```
`policy = ArticlePolicy.new(Article.first, user: User.first)`

This works fine: 
`policy.apply(:update?)` 
=> true

but this through an error:
`policy.apply(:edit?)` 
=> NoMethodError (undefined method `edit?' for #<ArticlePolicy:0x00007fc4bc564158>)

Thanks for your help.

Best,
Benoit

Ruby Version: 2.5.1
Framework Version (Rails, whatever): 5.1.6
Action Policy Version: 0.2.0

**Comment by palkan** [comment]
Yes, this is the intended behaviour. From [the docs](https://actionpolicy.evilmartians.io/#/aliases):

>  An alias created with alias_rule is resolved at authorization time (during an authorize! or allowed_to? call), and it does not add an alias method to the class.

And the motivation behind it is below:

> That allows us to write tests easier, as we should only test the rule, not the alias–and to leverage caching better.

**Comment by palkan** [comment]
For that case it make sense to include `ActionPolicy::Behaviour` into a service and use `authorize!`. See [the example](https://actionpolicy.evilmartians.io/#/non_rails).
