### ISSUE TITLE
Passing authorisation context when calling allowed_to? within policy

### ISSUE THREAD

**Issue by brendon** [palkan/action_policy#36]
Currently if one called `allowed_to?` from with an existing policy rule, the authorisation context doesn't get passed to the other policy (at least that's how it behaves). Is there an easy way to inject the authorisation context into the sub-policy?

**Comment by palkan** [comment]
> the authorisation context doesn't get passed to the other policy (at least that's how it behaves)

Could you please provide an example?

Authorization contexts is passed to _nested_ policies (see this testhttps://github.com/palkan/action_policy/commit/bacaa993d3fc25fdc67ad2dd894f92e81cd3fa6d).

**Comment by palkan** [comment]
> but when we call allowed_to? on the PostPolicy the context is lost

Hm, in that case an exception is raised (`AuthorizationContextMissing`); unless you specified `allow_nil: true`.

Could you share your policy classes? Or propose a PR with the failing test

**Comment by brendon** [comment]
Thanks @palkan. I've made a failing test case PR: https://github.com/palkan/action_policy/pull/37

Hope it makes sense :)
