### ISSUE TITLE
Global admin namespace?

### ISSUE THREAD

**Issue by chrismanderson** [palkan/action_policy#42]
Playing around with this great gem, and I feel like I'm missing something. What's the recommended way of applying say an `Admin` namespace to every action in a controller?

So if I have 

```
class OrdersController
   def index
   end

   def show
   end
end
```

How to I make every action in the controller respond to a policy such as 

```
class AdminPolicy < ActionPolicy::Base
  authorize :admin

  default_rule :admin?

  def admin?
    allow! if user.admin?
  end
end
```

I tried things like `authorize :admin` and `authorize! :admin` in the controller, but that can't find a policy, and I feel like I'm missing something obvious. Thanks!

**Comment by palkan** [comment]
There is no default lookup mechanism for symbols (like in Pundit). At least, yet.

Take a look at the discussion here https://github.com/palkan/action_policy/issues/17#issuecomment-398693964. There are some proposed solutions.

**Comment by palkan** [comment]
Symbol lookup has been added in #46 and will be released in the next version.
