### ISSUE TITLE
Question: Calling a scope from another scope

### ISSUE THREAD

**Issue by louim** [palkan/action_policy#53]
Hey!

We are currently migrating from Pundit to ActionPolicy and I found a case I'm not sure how to handle. Here is an simplified example of what I'm trying to do
```ruby
relation_scope(:edit) do |scope|
  # The next line is what I would like to do
  teachers = authorized(Teacher.all, as: :edit)
  scope
    .joins(:teachers)
    .where(teacher_id: teachers)
end
```
Is there a way currently to do that?

**Comment by palkan** [comment]
Hey! That's interesting case.

The `authorized` method is the part of `ActionPolicy::Behaviour`, and if you include the behaviour that would likely break the functionality.

I think, it makes sense to extract _scoping_ behaviour from the core behaviour, thus making possible to include it into policies classes. That's the first option.

Another option (which I'd prefer) is to build policy class manually and use it:

```ruby
# note that you should use `name` here instead of `as`
teachers = policy_for(Teacher).apply_scope(Teacher.all, name: :edit)
```

**Comment by louim** [comment]
Thanks for the quick answer! Your option 2 is actually pretty much what we're doing currently with Pundit  (`TeacherPolicy::Scope.new(user, Teacher).edit`), which is good enough for me 😄.

**Comment by louim** [comment]
Sorry for reopening this. I ended up having to do:
```
policy_for(record: Teacher).apply_scope(Teacher.all, type: :active_record_relation, name: :edit)
```
because `policy_for` expect the `record` parameter, and `type` seems to be a required parameter too. Maybe there should be less verbose way to do this?
