### ISSUE TITLE
Policy Caching will trigger a database request when using `authorized`.

### ISSUE THREAD

**Issue by louim** [palkan/action_policy#55]
### Tell us about your environment

**Ruby Version:**
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

**Framework Version (Rails, whatever):**
Rails 5.1.6.1

**Action Policy Version:**
Master Branch, 913b6623ec467b0d5b107a7b543d21c59724ae76

### What did you do?
Lets say we have a model `EventRecord`, with hundred of thousands of records in the database. 

Consider this simple policy:
```
class EventRecordPolicy < ApplicationPolicy
  relation_scope do |scope|
    if user.admin?
      scope
    else
      scope.none
    end
  end
end
```
And using `authorized(EventRecord.all)` in the controller to have scope type inferred automatically.
### What did you expect to happen?
No request is made until the scope is actually used. 

### What actually happened?
The following request is always issued, whether or not the scope is actually used.
`SELECT COUNT(*) AS "size", MAX("events"."updated_at") AS timestamp FROM "events"`. This request has the potential of being really expensive if there's a large quantity of records being queried.

### Why does it happen?
As part of the Memoization that happens here,
https://github.com/palkan/action_policy/blob/21b97a0f57396855ed0b5fd85c38cd1c40325199/lib/action_policy/behaviours/memoized.rb#L39-L41
The `cache_key` method is invoked on the `record`, which in this case is an `ActiveRecord::Relation` https://github.com/palkan/action_policy/blob/21b97a0f57396855ed0b5fd85c38cd1c40325199/lib/action_policy/ext/policy_cache_key.rb#L16
`ActiveRecord::Relation` happens to also implement a [`cache_key` method](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-cache_key), which will trigger the above request since the collection isn't already loaded. In the end, even if the scope isn't used (ex: chained with `.none` like in the policy above), the potentially costly request will already have fired.

**Comment by palkan** [comment]
Thanks for catching this!

Fixed in master. Now `policy_cache_key` is explicitly defined for `ActiveRecord::Relation`.
Added a note about potential performance caveat to the docs.
