### ISSUE TITLE
Q: How to authorize render json?

### ISSUE THREAD

**Issue by matissg** [palkan/action_policy#66]
I'm using [Ajax Datatables Rails](https://github.com/jbox-web/ajax-datatables-rails) gem and was wondering, how do I apply Action Policy for my index action where I would need to respond with JSON? I'd like to restrict access to the path and getting records via DataTable (retrieves JSON).

My `offers_controller.rb` index action looks like this:
```
  def index
    respond_to do |format|
      format.html
      format.json { render json: Seller::OfferDatatable.new(
        params, view_context: view_context,
        status: params[:type],
        sellers: current_user.companies.ids
        ) }
    end
  end
```
In `offer_datatable.rb` I'm getting my records with:
```
  def get_raw_records
    Seller::Offer.status(status).sellers(sellers)
                 .order(published_at: :desc)
  end
```
and I don't have instance variable @offers to authorize.

I'd be happy for any hint. Thank you.

**Comment by matissg** [comment]
Ok, one thing I can do is something like this:
```
  def index
    redirect_to errors_path unless allowed_to?(:index?, Seller::Offer)
    respond_to do |format|
      format.html {}
      format.json { render json: Seller::OfferDatatable.new(
        params, view_context: view_context,
        status: params[:type],
        sellers: current_user.companies.ids
        ) }
    end
  end
```
Is this good enough? Basically I'm sending user to my `ErrorsController#no_access` where I render status 401.

**Comment by palkan** [comment]
If you need only to restrict the access to the action, you can call:

```ruby
authorize! Seller::Offer # which checks for `index?` rule by default
```

So, it's almost the same as using `allowed_to?(:index?, Seller::Offer)`; the difference is that in case of `authorize!` the `ActionPolicy::Unauthorized` errors is raised.

**Comment by matissg** [comment]
@palkan Great, thank you. Looks like this is what I needed.
