### ISSUE TITLE
[question] JSON of permissions per object

### ISSUE THREAD

**Issue by alaz** [palkan/action_policy#69]
Hello,

This is not an issue, but rather a request for advice. I would like to have an API endpoint that returns JSON of actions allowed for an object (for example a posting) and I am going to use that information in order to enable/disable actions in frontend.

So far I've come up with something like the following.

`posts_controller.rb`:

```ruby
  def permissions
    load_post!
    authorize! @post

    hash = %w[destroy edit full index new permissions preheader quote raw text show].map do |k|
      [k, allowed_to?("#{k}?".to_sym, @post)]
    end.to_h

    render formats: :json, json: hash.as_json
  end
```

which will result in something like

```json
{"destroy": false,
 "edit": false,
 "full": true,
 "index": true,
 "new": true,
 "permissions": true,
 "preheader": true,
 "quote": true,
 "raw": true,
 "text": true,
 "show": true}
```

Can I do it better? I would appreciate any advices on the approach and its implementation.

Regards,
Alexander

**Comment by palkan** [comment]
Hey!

First, question: do you use any serialisation libraries? (e.g. `active_model_serializers`, etc.).

I see two possible improvements here: adding more context to the payload (by including [failure reasons](https://actionpolicy.evilmartians.io/#/reasons)) and extracting serialization logic into its own class (serializer or whatever).

Let's start with failure reasons.

We have a similar feature in our existing app: exposing authorization rules (or _permissions_) to clients.
We found that it could be very helpful to include rejection messages to the permissions payload as well (i.e. not only `true` | `false`).
This way our clients a) should not be responsible for generating messages (we use I18n for that) b) could use failure reasons code to ask users for different actions.

The idea is described in this slide deck: https://speakerdeck.com/palkan/seattle-dot-rb-2019-a-denial?slide=122 (the `action_policy-graphql` gem hasn't been published yet, though the main features are shown there).

Now, let's sketch the `PostPermissionsSerializer`.

The goal is to _extract_ this logic from the controller (for reusability and testability):

```ruby
def permissions
    load_post!
    authorize! @post

    # `authorization_context` is used by Action Policy helpers to perform authorization
    render formats: :json, json: PostPermissionsSerializer.new(@post).serialize_for(authorization_context)
end
```

Then our serializer class could look like this:

```ruby
# base class
class ApplicationPermissionsSerializer
   # add `allowed_to?` helper (and all the policy lookup functionality)
   include ActionPolicy::Behaviour

   class << self
     attr_reader :rules

     def expose_rules(*rules)
       # very basic implementation; ideally we need to handle inheritance here
       @rules = rules
     end
   end

   def initialize(target)
     @target = target
   end

   def serialize_for(context)
     policy = policy_for(target)
     self.class.rules.each_with_object({}) do |rule, acc|
       # invoke rule (that populates the policy.result object)
       policy.apply(rule)
       acc[rule] = policy.result.as_json # not sure what this method returns, we should probably add support fro this
       acc
     end
   end
end

# post permissions class
class PostPermissionsSerializer < ApplicationPermissionsSerializer
   expose_rules %i[destroy edit full index new permissions preheader quote raw text show]
end
```

**Comment by alaz** [comment]
I am using JBuilder when I need to generate more complicated JSON. TBH it suffices so far.

I thought about permission reasons as well. Many thanks to you for the detailed description of your approach and a link to the slides. I believe I have enough information to come up with something alike for my needs.

Great presentation! 👍

**Comment by alaz** [comment]
Thank you again for the ideas. I still use rather simplistic serialization and do not seem to need more complicated approaches, so my code looks like the following

```ruby
  def permissions_for(object, actions, **options)
    policy = policy_for record: object, **options
    actions.map do |action|
      rule = policy.resolve_rule "#{action}?".to_sym
      policy.apply rule
      res = if policy.result.success?
              true
            # FIXME: `policy.result.reasons` is always empty
            # elsif policy.result.reasons.present?
            #   policy.result.reasons.details
            else
              false
            end
      [action, res]
    end.to_h
  end
```

The problem is outlined in the snippet above. I cannot retrieve failure reasons out of `policy.result`, because the list is always empty. Am I missing something?

**Comment by palkan** [comment]
> I cannot retrieve failure reasons out of policy.result, because the list is always empty. Am I missing something?

How do your policy rules look like? Failure reasons are only populated if you have `check?` and `allowed_to?` in your rules definitions.

**Comment by alaz** [comment]
Good catch. Thanks!
