### ISSUE TITLE
Ability to pass decorated object

### ISSUE THREAD

**Issue by timurvafin** [palkan/action_policy#7]
It will be great to pass decorated object to the public methods in case we use something like `drapper`.

To implement this you need to try `to_model` on record before accessing record.
You can utilize `ActionView::ModelNaming` and `convert_to_model(record)`

**Comment by palkan** [comment]
Hi @timurvafin,

Could you please provide more context and/or a complete code example?

**Comment by aganov** [comment]
I'm drapper user too, but I don't think `action_policy` should have explicit support of it. After all, you should pass record (model) object, not decorated one...

@palkan Example context

```ruby
class PostsController < ApplicationController
  def index
    @posts = Post.all.decorate
  end

  def show
    # PostDecorator instance is passed to authorize
    authorize! @post = Post.find(1).decorate
  end
end
```

```erb
<% @posts.each do |post| %>
  <li><%= post.title %>
    <% if allowed_to?(:edit?, post) # PostDecorator instance is passed to allowed_to %>
      = link_to "Edit", post
    <% end %>
  </li>
<% end %>
```

**Comment by timurvafin** [comment]
This is mainly about how to use `allowed_to?` in the view with decorated object:

`allowed_to?(:edit?, post)` 
vs 
`allowed_to?(:edit?, post.to_model)`

**Comment by palkan** [comment]
@timurvafin Have you tried the proposed patch above? I think, having a this kind of example in the dos would be enough.

**Comment by timurvafin** [comment]
@palkan works as expected, thank you!

**Comment by palkan** [comment]
@timurvafin Would you like to add this example to the docs?

**Comment by palkan** [comment]
Closed by https://github.com/palkan/action_policy/commit/8af28606ed8f24a792bb98b652dad30cc4ce88f0
