### ISSUE TITLE
Add policy generator

### ISSUE THREAD

**Issue by nicolas-brousse** [palkan/action_policy#85]
Hi!

I'm currently locking to use `action_policy` instead of `pundit` for our new projects.  
And I notice that there is no generator to create new policies `rails g policy user`.

Is there any particular reason? Does it something that could interest you?

**Comment by palkan** [comment]
> Does it something that could interest you?

That would be a great addition to Rails integration. Do you want to propose a PR?

**Comment by nicolas-brousse** [comment]
Yes, I could work on a PR. I'll try to found some time in the following days.
