### ISSUE TITLE
RSpec view spec, missing policy authorization context

### ISSUE THREAD

**Issue by nicolas-brousse** [palkan/action_policy#88]
### Tell us about your environment

**Ruby Version:** ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Framework Version (Rails, whatever):** Rails 6.0.0

**Action Policy Version:** 0.3.2

### What did you do?

I'm testing some views of my app that use `allowed_to?` helper.

### What did you expect to happen?

Having my test working normally. Or to know what could I change in my test to avoid this.

### What actually happened?

```
Failures:

  1) admin/users/edit.html.slim displays user#edit correctly 
     Failure/Error: - if allowed_to?(:edit?, @user)
     
     ActionView::Template::Error:
       Missing policy authorization context: user
     # ./app/views/admin/users/_form.html.slim:19:in `block in _app_views_admin_users__form_html_slim__2614983762995680549_70232191255660'
     # ./app/views/admin/users/_form.html.slim:9:in `_app_views_admin_users__form_html_slim__2614983762995680549_70232191255660'
     # ./app/views/admin/users/edit.html.slim:1:in `_app_views_admin_users_edit_html_slim__69430724083846117_70232190867720'
     # ./spec/views/admin/users/edit.html.slim_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ActionPolicy::AuthorizationContextMissing:
     #   Missing policy authorization context: user
     #   ./app/views/admin/users/_form.html.slim:19:in `block in _app_views_admin_users__form_html_slim__2614983762995680549_70232191255660'
```

**Comment by palkan** [comment]
This is a know limitation of view specs. You should provide the information required for helpers manually.

Something like this:

```ruby
view.stub(:current_user).and_return(user)

# or stub allowed_to? explicitly
```

See related issues/questions:
- https://stackoverflow.com/questions/30305899/devise-and-rspec-accessing-current-user-in-specs
- https://github.com/ryanb/cancan/issues/598
- https://stackoverflow.com/questions/11651232/how-to-stub-or-mock-authlogic-current-user-in-view-specs

**Comment by nicolas-brousse** [comment]
Thanks for the tips. I search and tried some stuff but didn't found these issues/questions.

To complete, `view` doesn't works. I'd to use `controller`instead, like following:

```ruby
controller.stub(:current_user).and_return(user)
```

Does it something that could be added in documentation?

**Comment by palkan** [comment]
> Does it something that could be added in documentation?

Although it's not related to this particular gem, let's add it (along with the link to this issue).
