### ISSUE TITLE
mistype and default_rule and manage?

### ISSUE THREAD

**Issue by skojin** [palkan/action_policy#92]
I just have problem, because I make mistype, and instead of ```create?``` type ```create```.
And I expected that it will fail, but instead it fallback to default manage? rule. For me this behaviour looks strange and add unexpected magic.

I off this behaviour if ```default_rule nil```

**Comment by palkan** [comment]
This behavior is described in the documentation: [here](https://actionpolicy.evilmartians.io/#/custom_policy) and [here](https://actionpolicy.evilmartians.io/#/aliases?id=default-rule).

The best way to avoid such problems is to [add tests](https://actionpolicy.evilmartians.io/#/testing) 😉
