### ISSUE TITLE
Testing authorization of not yet persisted records

### ISSUE THREAD

**Issue by louim** [palkan/action_policy#97]
### Tell us about your environment

**Ruby Version:**
2.6.5

**Action Policy Version:**
0.3.4

### What did you do?
Consider the following controller:

```ruby
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    authorize! @post
    if @post.save
      redirect_to @post
    else
      render :show
    end
  end
end
```
### What did you expect to happen?

```ruby
it "authorize the post do
  expect { post :create, params: { post: post_payload } }
    .to be_authorized_to(:create?, what_do_i_use_here)
end
```

The examples all cover an existing object, but i'm not exactly sure of what I should be comparing in `what_do_i_use_here`?

**Comment by palkan** [comment]
You can use `an_instance_of(Post)` here.

Though I'd recommend to `authorize! Post` instead: authorization shouldn't depend on the input but on the action itself and a subject (which is missing in this case).

**Comment by louim** [comment]
Hey!
Thank you for the answer. While I agree that it's generally better to `authorize! Post` on initial `create`,  in this case I need to authorize associations on the record that is being created. My policy looks somewhat like this:

```ruby
class PostPolicy < ApplicationPolicy
  def create?
    allowed_to?(:update?, record.author) && other_conditions
  end
end
```

**Comment by louim** [comment]
```
subject(:create) { post :create, params: { post: post_payload } }
it "authorize the post do
  expect { create }.to be_authorized_to(:create?, an_instance_of(Post))
end
```
Maybe I spoke too soon, because passing `an_instance_of(Post)` result in the following message:
```
ActionPolicy::NotFound:
Couldn't find policy class for #<RSpec::Matchers::AliasedMatcher:0x00007ffcb7e13f28 @description_block=#<Proc:0x00007ffcbb0119f8@/Users/louim/.gem/ruby/2.6.5/gems/rspec-expectations-3.6.0/lib/rspec/matchers/dsl.rb:31 (lambda)>, @base_matcher=#<RSpec::Matchers::BuiltIn::BeAnInstanceOf:0x00007ffcb7e13f50 @expected=Post(some_attributes), @matcher_name=:an_instance_of>> (RSpec::Matchers::AliasedMatcher)
```
 Because it can't infer the policy from the instance matcher, which make sense to me, so I tried:
```
subject(:create) { post :create, params: { post: post_payload } }
it "authorize the post do
  expect { create }.to be_authorized_to(:create?, an_instance_of(Post)).with(PostPolicy)
end
```
and I got
```
expected an instance of Post to be authorized with PostPolicy#create?, but the following calls were encountered:
        - #<Post id: 17439, some_more_post_attributes> was authorized with PostPolicy#create?
```

**Comment by palkan** [comment]
Looks like we do not recognize compound matchers in `be_authorized_to`. Will fix it.

**Comment by louim** [comment]
Thanks!
